<?php

   /**
    * Implements hook_install().
    */
    function membershipvalidator_install() {
        $ret = array();

        $spec = array(
            'type' => 'int',
            'size' => 'tiny',
            'not null' => FALSE,
            'description' => 'This field describes how a field is acting when it\'s part of the frequency or the amount paid by a member)'
        );

        db_add_field( "webform_component", "membership_info", $spec );
    }

?>
