<?php

   /**
    * Implementation of hook_webform_validation_validators().
    */
    function minimumvalue_webform_validation_validators() {
        return
            array(
                'validate_minimum_value' => array(
                    'name' => 'Validates Minimum Amount',
                    'description' => t( 'Verifies that the minimum amount is correct due to the selected frequency.' ),
                    'component_types' => array( 'int', 'number' ) )
             );
    }

   /**
    * Implementation of hook_webform_validation_validate().
    */
    function minimumvalue_webform_validation_validate($validator_name, $items, $components, $rule ) {

        // Definition of the minimum amounts
        $min_amount = floatval(0.01);

        // Errors
        $error = 'Ha habido un error con la cantidad aportada introducida. Revísala, por favor. ¡Gracias!' ;
        $errors = array();

        if ( $items ) {
            switch ( $validator_name ) {
                case 'validate_minimum_value':
      				    // Define one variable per field we want to check
                  $donativo = 0;
      		        foreach ( $items as $key => $value ) {
                        $value_def = str_replace(",", ".", $value);
              		      $donativo = floatval($value_def);
      		        }
      				    if( $donativo < $min_amount ){
                        // Mark the third box as an error, that is the other amount one
                        foreach( $items as $key => $value){
                          $errors[$key] = t( $error,
                              array( '%item' => $components[ $key ][ "name" ] ) );
                        }
      				    }
                  return $errors;
                  break;
              }
          }
    }
?>
